/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;

import std.stream, std.string, std.stdio, tocommon;

class FormSecret: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.picturebox.PictureBox pictureBox1;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeFormSecret();
		
		//@  Other FormSecret initialization code here.
		
	}
	
	
	private void initializeFormSecret()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		formBorderStyle = dfl.all.FormBorderStyle.NONE;
		showInTaskbar = false;
		startPosition = dfl.all.FormStartPosition.CENTER_PARENT;
		text = "Form Secret";
		clientSize = dfl.all.Size(302, 452);
		//~DFL dfl.picturebox.PictureBox=pictureBox1
		pictureBox1 = new dfl.picturebox.PictureBox();
		pictureBox1.name = "pictureBox1";
		pictureBox1.dock = dfl.all.DockStyle.FILL;
		pictureBox1.bounds = dfl.all.Rect(0, 0, 302, 452);
		pictureBox1.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
		pictureBox1.click ~= &onClickPicture;
		pictureBox1.image = dfl.drawing.Picture.fromStream(FS.patch["patcher/secret.jpg"].open);
	}
	
	void onClickPicture(Control c, EventArgs ea) {
		this.close();
	}
}

