/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

import dfl.all;

import std.stream, std.file, std.stdio, std.thread;
import std.c.windows.windows;

class SoundT : Thread {
	ubyte[] d;
	
	this(ubyte[] d) {
		this.d = d;
	}
	
	override int run() {
		PlaySoundA(cast(char*)d.ptr, null, SND_MEMORY); 
		return 0;
	}
}

void PlaySound(ubyte[] data, bool async = true) {
	PlaySoundA(cast(char*)data.ptr, null, SND_MEMORY | (async ? SND_ASYNC : 0)); 
	//auto t = new SoundT(data); t.start();
}

Image appBG;
ubyte[] sndHover, sndClick, sndExit;

class MyButton : Button {
	void onMouseEnter(MouseEventArgs mea) {
		PlaySound(sndHover);
	}

	void onClick(EventArgs mea) {
		PlaySound(sndClick);
		super.onClick(mea);
	}
}

version(Windows) {
	extern(Windows) HINSTANCE ShellExecuteA(HWND hwnd, LPCSTR lpOperation, LPCSTR lpFile, LPCSTR lpParameters, LPCSTR lpDirectory, INT nShowCmd);
}

class MyLabel : Label {
	this() {
		foreColor = Color.fromRgb(0xFFFFFF);
	}
	override void onPaintBackground(PaintEventArgs pea) {
		auto g = pea.graphics;
		appBG.draw(g, Point(-left, -top));
		//g.drawRectangle(new Pen(Color.fromRgb(0x000000)), pea.clipRectangle);
		//g.fillRectangle(new SolidBrush(Color.fromArgb(0x00, 0x7F, 0x7F, 0x7F)), pea.clipRectangle);
	}
	
	override void onPaint(PaintEventArgs pea) {
		super.onPaint(pea);
	}
}

class MyForm: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	MyButton button1;
	MyButton button2;
	MyButton button3;
	MyLabel label3;
	MyLabel label4;
	MyLabel label5;
	MyLabel label6;
	MyLabel label7;
	//~Entice Designer variables end here.
	
	void checkInput() {
		label7.text = "";
		if (label3.text == label4.text) {
			label7.text = "La ISO de salida no debe coincidir con la de entrada";
		}
		if (label3.text[0] == '<') return;
		if (label4.text[0] == '<') return;
		button1.enabled = (!label7.text.length);
	}
	
	this()
	{
		initializeMyForm();
		
		setClientSizeCore(640, 480);
		
		//@  Other MyForm initialization code here.
		
		appBG = dfl.drawing.Picture.fromStream(new File("/toa/patch/patcher/bg.jpg"));

		sndHover = cast(ubyte[])read(r"C:\toa\patch\patcher\cursor1.wav");
		sndClick = cast(ubyte[])read(r"C:\toa\patch\patcher\cursor2.wav");
		sndExit  = cast(ubyte[])read(r"C:\toa\patch\patcher\cursor3.wav");
		
		label5.cursor = Cursors.hand;
		label5.click ~= &ttClick;

		label6.cursor = Cursors.hand;
		label6.click ~= &toaClick;
		
		button2.click ~= &onSelectOriginal;
		button3.click ~= &onSelectPatched;
	}
	
	void ttClick(Control o, EventArgs ea) {
		PlaySound(sndClick);
		ShellExecuteA(null, "open", "http://tales-tra.com/", null, null, SW_SHOWNORMAL);
	}

	void toaClick(Control o, EventArgs ea) {
		PlaySound(sndClick);
		ShellExecuteA(null, "open", "http://toa.tales-tra.com/", null, null, SW_SHOWNORMAL);
	}
	
	override void onClosing(CancelEventArgs ea) {
		PlaySound(sndExit, false);
	}
	
	void onSelectOriginal(Control c, EventArgs ea) {
		OpenFileDialog fd = new OpenFileDialog();
		fd.filter = "Imagen de CD (*.iso;*.mdf)|*.iso;*.mdf|Todos los Archivos (*.*)|*.*";
		fd.title = "Selecciona ISO";
		//fd.initialDirectory = getDirName(textBox1.text);
		//fd.fileName = textBox1.text;
		if (fd.showDialog(this) == DialogResult.OK) {
			label3.text = fd.fileName;
			PlaySound(sndClick);
		} else {
			PlaySound(sndExit);
		}
		checkInput();
	}		

	void onSelectPatched(Control c, EventArgs ea) {
		SaveFileDialog fd = new SaveFileDialog();
		fd.filter = "Imagen de CD (*.iso)|*.iso|Todos los Archivos (*.*)|*.*";
		fd.title = "Selecciona ISO";
		fd.defaultExt = "iso";
		//fd.fileName = textBox2.text;
		if (fd.showDialog(this) == DialogResult.OK) {
			label4.text = fd.fileName;
			PlaySound(sndClick);
		} else {
			PlaySound(sndExit);
		}
		checkInput();
	}	

	override void onPaintBackground(PaintEventArgs pea) { }
	
	override void onPaint(PaintEventArgs pea) {
		auto g = pea.graphics;
		appBG.draw(g, Point(0, 0));
	}
	
	private void initializeMyForm()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		formBorderStyle = dfl.all.FormBorderStyle.FIXED_SINGLE;
		maximizeBox = false;
		startPosition = dfl.all.FormStartPosition.CENTER_SCREEN;
		text = "My Form";
		clientSize = dfl.all.Size(634, 454);
		//~DFL MyButton:dfl.button.Button=button1
		button1 = new MyButton();
		button1.name = "button1";
		button1.enabled = false;
		button1.font = new dfl.all.Font("Georgia", 12f, dfl.all.FontStyle.REGULAR);
		button1.text = "Parchear";
		button1.bounds = dfl.all.Rect(232, 384, 176, 40);
		button1.parent = this;
		//~DFL MyButton:dfl.button.Button=button2
		button2 = new MyButton();
		button2.name = "button2";
		button2.font = new dfl.all.Font("Georgia", 9f, dfl.all.FontStyle.REGULAR);
		button2.text = "Seleccionar...";
		button2.bounds = dfl.all.Rect(448, 280, 112, 24);
		button2.parent = this;
		//~DFL MyButton:dfl.button.Button=button3
		button3 = new MyButton();
		button3.name = "button3";
		button3.font = new dfl.all.Font("Georgia", 9f, dfl.all.FontStyle.REGULAR);
		button3.text = "Seleccionar...";
		button3.bounds = dfl.all.Rect(448, 312, 112, 24);
		button3.parent = this;
		//~DFL MyLabel:dfl.label.Label=label3
		label3 = new MyLabel();
		label3.name = "label3";
		label3.enabled = false;
		label3.font = new dfl.all.Font("Georgia", 9f, dfl.all.FontStyle.REGULAR);
		label3.foreColor = dfl.all.Color(40, 40, 40);
		label3.text = "<Selecciona ISO>";
		label3.textAlign = dfl.all.ContentAlignment.MIDDLE_LEFT;
		label3.bounds = dfl.all.Rect(104, 280, 328, 24);
		label3.parent = this;
		//~DFL MyLabel:dfl.label.Label=label4
		label4 = new MyLabel();
		label4.name = "label4";
		label4.enabled = false;
		label4.font = new dfl.all.Font("Georgia", 9f, dfl.all.FontStyle.REGULAR);
		label4.foreColor = dfl.all.Color(40, 40, 40);
		label4.text = "<Selecciona ISO>";
		label4.textAlign = dfl.all.ContentAlignment.MIDDLE_LEFT;
		label4.bounds = dfl.all.Rect(104, 312, 328, 24);
		label4.parent = this;
		//~DFL MyLabel:dfl.label.Label=label5
		label5 = new MyLabel();
		label5.name = "label5";
		label5.backColor = dfl.all.Color(0, 0, 0);
		label5.bounds = dfl.all.Rect(152, 144, 328, 48);
		label5.parent = this;
		//~DFL MyLabel:dfl.label.Label=label6
		label6 = new MyLabel();
		label6.name = "label6";
		label6.backColor = dfl.all.Color(255, 0, 0);
		label6.bounds = dfl.all.Rect(208, 24, 208, 120);
		label6.parent = this;
		//~DFL MyLabel:dfl.label.Label=label7
		label7 = new MyLabel();
		label7.name = "label7";
		label7.font = new dfl.all.Font("Georgia", 13f, dfl.all.FontStyle.REGULAR);
		label7.foreColor = dfl.all.Color(255, 220, 220);
		label7.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
		label7.bounds = dfl.all.Rect(104, 344, 456, 32);
		label7.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}


int main()
{
	int result = 0;
	
	try
	{
		Application.enableVisualStyles();
		
		//@  Other application initialization code here.
		
		Application.run(new MyForm());
	}
	catch(Object o)
	{
		msgBox(o.toString(), "Fatal Error", MsgBoxButtons.OK, MsgBoxIcon.ERROR);
		
		result = 1;
	}
	
	return result;
}

